export {default as Navbar} from './Layout/Navbar'
export {default as Footer} from './Layout/Footer'
export {default as NavDots} from './NavDots'
export {default as SocialMedia} from './SocialMedia'
export {default as SmoothLonk} from './SmoothLink'